### ISSUE TITLE
Even Commits 

### ISSUE THREAD

**Issue by Albadylic** [fac18/week6-mepl#39]
On the insights tab, it tells us how many commits each person in your team has done. You've had a busy week @kin-au ! :computer: 

Try to keep these even by swapping machines and pairs often :balance_scale: 

![commits](https://user-images.githubusercontent.com/43413852/70315963-94042900-1812-11ea-9a0d-45674b7028fe.png)

**Comment by kin-au** [comment]
This was my fault when setting up the repo :clown_face: fake news

**Comment by kin-au** [comment]
I've not actually been busy at all

**Comment by marialani** [comment]
[](https://media.giphy.com/media/OqAeQrGmU7lS6tENnQ/giphy.gif)
